### PR TITLE
add eric eggplant image and co-op description

### PR DESCRIPTION
**Pull request by ehao1**
Added eggplanted image to assets
Replaced tina with eggplanted in FilterPage.js
Added a brief mission statement and description to Eric's Eggplants

image

### CODE REVIEW

**Review by rrrliu — CHANGES_REQUESTED** [review]
sorry forgot to mention in slack, but can u change ur lat/lon to be in Maryland 👀

**Comment by rrrliu** [comment]
also EGG PLANT hahahah

**Comment by ehao1** [comment]
The two coordinates are already in Maryland

**Comment by rrrliu** [comment]
uh looks like [China](https://www.google.com/maps/place/39%C2%B005'52.1%22N+77%C2%B014'05.3%22E/@35.9659484,87.654041,3z/data=!4m5!3m4!1s0x0:0x0!8m2!3d39.0978!4d77.2348) to me

**Comment by rrrliu** [comment]
look at the map view -- there's no marker in Maryland

**Comment by ehao1** [comment]
OH NO my coordinate was in W, not E lemee fix that rn

**Review by rrrliu — DISMISSED** [review]
gj sir

**Review by rrrliu — APPROVED** [review]

**Pull request merged**
